package ar.com.atletismo.ui;

import ar.com.atletismo.dominio.Aspirante;
import ar.com.atletismo.dominio.Escuela;
import ar.com.atletismo.utils.DateUtils;
import ar.com.atletismo.utils.NumericUtils;
import ar.com.atletismo.utils.StringUtils;
import javax.swing.JOptionPane;

/**
 *
 * @author ariel
 */
public class PantallaNuevoAspirante extends javax.swing.JDialog {

    private PantallaRegistroAspirantes parentFrame;
    private Aspirante aspirante;
    
    public PantallaNuevoAspirante(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.parentFrame = (PantallaRegistroAspirantes)parent;
        initComponents();
        this.aspirante = null;
    }

    public Aspirante getAspirante() {
        return this.aspirante;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpSexo = new javax.swing.ButtonGroup();
        panelDatosAspirante = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtFechaDeNacimiento = new javax.swing.JTextField();
        lblFechaDeNacimiento = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        optMasculino = new javax.swing.JRadioButton();
        optFemenino = new javax.swing.JRadioButton();
        lblDni = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        panelBotones = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblMensajeError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo Aspirante");

        lblNombre.setText("Nombres");

        lblApellido.setText("Apellidos");

        lblDireccion.setText("Dirección");

        lblFechaDeNacimiento.setText("Fecha de nacimiento");

        lblSexo.setText("Sexo");

        btnGrpSexo.add(optMasculino);
        optMasculino.setText("Masculino");
        optMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optMasculinoActionPerformed(evt);
            }
        });

        btnGrpSexo.add(optFemenino);
        optFemenino.setSelected(true);
        optFemenino.setText("Femenino");

        lblDni.setText("D.N.I.");

        javax.swing.GroupLayout panelDatosAspiranteLayout = new javax.swing.GroupLayout(panelDatosAspirante);
        panelDatosAspirante.setLayout(panelDatosAspiranteLayout);
        panelDatosAspiranteLayout.setHorizontalGroup(
            panelDatosAspiranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosAspiranteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosAspiranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApellido)
                    .addComponent(lblDireccion)
                    .addComponent(lblFechaDeNacimiento)
                    .addComponent(lblSexo)
                    .addComponent(lblDni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosAspiranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre)
                    .addComponent(txtApellido)
                    .addComponent(txtDireccion)
                    .addComponent(txtFechaDeNacimiento)
                    .addGroup(panelDatosAspiranteLayout.createSequentialGroup()
                        .addComponent(optMasculino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optFemenino)
                        .addGap(0, 52, Short.MAX_VALUE))
                    .addComponent(txtDni))
                .addContainerGap())
        );
        panelDatosAspiranteLayout.setVerticalGroup(
            panelDatosAspiranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosAspiranteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelDatosAspiranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombre)
                    .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosAspiranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtApellido)
                    .addComponent(lblApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosAspiranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosAspiranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFechaDeNacimiento)
                    .addComponent(lblFechaDeNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosAspiranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelDatosAspiranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(optMasculino)
                        .addComponent(optFemenino))
                    .addComponent(lblSexo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosAspiranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDni)
                    .addComponent(lblDni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(btnAceptar)
                .addGap(36, 36, 36)
                .addComponent(btnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar)))
        );

        lblMensajeError.setForeground(new java.awt.Color(224, 18, 46));
        lblMensajeError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDatosAspirante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMensajeError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelDatosAspirante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMensajeError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String mensajeError = this.isDatosValidos();
        if (mensajeError==null) {
            Integer numeroDeDocumento = new Integer(this.txtDni.getText());
            // verifico si el aspirante eesta en el formulario actual
            Escuela escuela = this.parentFrame.existeAspiranteEnFrame(numeroDeDocumento);
            if (escuela!=null) {
                JOptionPane.showMessageDialog(this, "El Aspirante ya existe en el actual formulario en la escuela: " + escuela.getNombre(), "ASPIRANTE DUPLICADO", JOptionPane.ERROR_MESSAGE);
                return;
            }
            // verifico si aspirante ya esta registrado
            Aspirante aspirante = this.parentFrame.getGestorInscripcionAspirantes().buscarAspirantePorNumeroDeDocumento(numeroDeDocumento);
            if (aspirante!=null) {
                JOptionPane.showMessageDialog(this, "El Aspirante ya se encuentra registrado", "ASPIRANTE DUPLICADO", JOptionPane.ERROR_MESSAGE);
                return;
            }
            // el aspirante no esta registrado
            this.aspirante = new Aspirante();
            this.aspirante.setNombre(this.txtNombre.getText());
            this.aspirante.setApellido(this.txtApellido.getText());
            this.aspirante.setDireccion(this.txtDireccion.getText());
            this.aspirante.setFechaDeNacimiento(DateUtils.getDate(this.txtFechaDeNacimiento.getText()));
            this.aspirante.setNumeroDeDocumento(new Integer(this.txtDni.getText()));
            this.aspirante.setSexo((this.optFemenino.isSelected())?"F":"M");
            this.dispose();
        } else {
            this.lblMensajeError.setText(mensajeError);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private String isDatosValidos() {
        String mensaje = null;
        if (StringUtils.isEmpty(this.txtNombre.getText())) {
            mensaje = "El nombre es obligatorio.";
        } else if (StringUtils.isEmpty(this.txtApellido.getText())) {
            mensaje = "El apellido es obligatorio.";
        } else if (StringUtils.isEmpty(this.txtDireccion.getText())) {
            mensaje = "La dirección es obligatoria.";
        } else if (!DateUtils.fechaValida(this.txtFechaDeNacimiento.getText())) {
            mensaje = "La fecha de nacimiento es obligatoria y su formato debe ser DD/MM/AAAA.";
        } else if (!NumericUtils.isNumeric(this.txtDni.getText())) {
            mensaje = "El D.N.I. es obligatorio y debe ser numérico (sin separar).";
        }
        return mensaje;
    }
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void optMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optMasculinoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.ButtonGroup btnGrpSexo;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblFechaDeNacimiento;
    private javax.swing.JLabel lblMensajeError;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JRadioButton optFemenino;
    private javax.swing.JRadioButton optMasculino;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelDatosAspirante;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtFechaDeNacimiento;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
